class Links:
    ADD_REMOVE = 'https://the-internet.herokuapp.com/add_remove_elements/'
    BROKEN_IMAGES = 'https://the-internet.herokuapp.com/broken_images'
    CHECKBOXES = 'https://the-internet.herokuapp.com/checkboxes'
    CONTEXT_MENU = 'https://the-internet.herokuapp.com/context_menu'
    DRAG_AND_DROP = 'https://the-internet.herokuapp.com/drag_and_drop'
    DROPDOWN_LIST = 'https://the-internet.herokuapp.com/dropdown'
    KEY_PRESSES = 'https://the-internet.herokuapp.com/key_presses'
    DISAPPEARING_ELEMENTS = 'https://the-internet.herokuapp.com/disappearing_elements'
    DYNAMIC_CONTENT = 'https://the-internet.herokuapp.com/dynamic_content'
    DYNAMIC_LOADING = 'https://the-internet.herokuapp.com/dynamic_loading'
    DYNAMIC_LOADING_2 = 'https://the-internet.herokuapp.com/dynamic_loading/2'
    ENTRY_AD = 'https://the-internet.herokuapp.com/entry_ad'
    EXIT_INTENT = 'https://the-internet.herokuapp.com/exit_intent'
    FRAMES = 'https://the-internet.herokuapp.com/frames'
    FRAMES_NESTED = 'https://the-internet.herokuapp.com/nested_frames'
    FROM_AUTH = 'https://the-internet.herokuapp.com/login'
    JS_ALERT = 'https://the-internet.herokuapp.com/javascript_alerts'